import exterior from './assets/exterior.jpg'
import bedroom from './assets/bedroom.jpg'
import bathroom from './assets/bathroom.jpg'
import dining from './assets/dining.jpg'
import kitchen from './assets/kitchen.jpg'
import slide1 from './assets/slide1.jpg'
import slide2 from './assets/slide2.jpg'
import slide3 from './assets/slide3.jpg'
import slide4 from './assets/slide4.jpg'
import slide5 from './assets/slide5.jpg'

const myProperties = [
    {
        id: 1,
        img: "./assets/house1.jpg",
        describe: 'Modern Spacious Villa',
        locate: 'Como Residencies, Palm Jumeirah',
        lat: 25.075134, lng: 55.132973,
        beds: '3',
        baths: '4',
        garage: '5',
        size: '5000',
        price: '3,500,000',
        slides: [
          {id: 1, img: exterior, title: "Main View"},
          {id: 2, img: slide1, title: "View 1"},
          {id: 3, img: slide2, title: "View 2"},
          {id: 4, img: slide3, title: "View 3"},
          {id: 5, img: slide4, title: "View 4"},
          {id: 6, img: slide5, title: "View 5"},
        ],
        overview: 'Indulge in the epitome of luxury in this stunning Dubai mansion with a captivating pool. Lavish interiors, breathtaking city views, and a serene outdoor oasis await you. Experience opulence and tranquility in one exceptional residence.',
        kitchen: kitchen,
        bedroom: bedroom,
        bathroom: bathroom,
        dining: dining,
    },
    {
        id: 2,
        img: "./assets/apartment.jpg",
        describe: 'Luxury Beachfront Apartment',
        locate: 'The Palm Tower, Palm Jumeirah',
        lat: 25.077828, lng: 55.137104,
        beds: '2',
        baths: '2',
        garage: '2',
        size: '1200',
        price: '2,200,000',
        slides: [
          {id: 1, img: exterior, title: "Main View"},
          {id: 2, img: slide1, title: "View 1"},
          {id: 3, img: slide2, title: "View 2"},
          {id: 4, img: slide3, title: "View 3"},
          {id: 5, img: slide4, title: "View 4"},
          {id: 6, img: slide5, title: "View 5"},
        ],
        overview: 'Experience the heartbeat of Dubai in this contemporary apartment nestled in Downtown. Enjoy seamless access to world-class shopping, entertainment, and cultural landmarks. With its sleek design and stunning city vistas, this urban abode offers the perfect blend of comfort and cosmopolitan living.',
        kitchen: kitchen,
        bedroom: bedroom,
        bathroom: bathroom,
        dining: dining,
      },
      {
        id: 3,
        img: "./assets/Jumeirah.jpg",
        describe: 'Contemporary Townhouse',
        locate: 'Jumeirah Village Circle',
        lat: 25.072568, lng: 55.139732,
        beds: '4',
        baths: '3',
        garage: '4',
        size: '2200',
        price: '1,800,000',
        slides: [
          {id: 1, img: exterior, title: "Main View"},
          {id: 2, img: slide1, title: "View 1"},
          {id: 3, img: slide2, title: "View 2"},
          {id: 4, img: slide3, title: "View 3"},
          {id: 5, img: slide4, title: "View 4"},
          {id: 6, img: slide5, title: "View 5"},
        ],
        overview: 'Elevate your living experience to new heights with this serene high-rise residence on the iconic Palm Jumeirah. Bask in stunning views of the Arabian Gulf, unwind in sophisticated interiors, and relish the luxury of exclusive beach access. This is the epitome of coastal living redefined.',
        kitchen: kitchen,
        bedroom: bedroom,
        bathroom: bathroom,
        dining: dining,
      },
      {
        id: 4,
        img: "./assets/ranchHome.jpg",
        describe: 'Spacious Family Home',
        locate: 'Arabian Ranches, Dubai',
        lat: 25.074916, lng: 55.140673,
        beds: '5',
        baths: '6',
        garage: '8',
        size: '6000',
        price: '4,500,000',
        slides: [
          {id: 1, img: exterior, title: "Main View"},
          {id: 2, img: slide1, title: "View 1"},
          {id: 3, img: slide2, title: "View 2"},
          {id: 4, img: slide3, title: "View 3"},
          {id: 5, img: slide4, title: "View 4"},
          {id: 6, img: slide5, title: "View 5"},
        ],
        overview: "Live your passion for golf and luxury in this elegant residence overlooking the fairways of Jumeirah Golf Estates. With its timeless design, premium finishes, and access to world-class amenities, this home is more than an address – it's a lifestyle statement for the golf aficionado.",
        kitchen: kitchen,
        bedroom: bedroom,
        bathroom: bathroom,
        dining: dining,
      },
      {
        id: 5,
        img: "./assets/apartment2.jpg",
        describe: 'Modern Apartment',
        locate: 'Dubai Marina',
        lat: 25.076344, lng: 55.134956,
        beds: '1',
        baths: '1',
        garage: '1',
        size: '800',
        price: '1,000,000',
        slides: [
          {id: 1, img: exterior, title: "Main View"},
          {id: 2, img: slide1, title: "View 1"},
          {id: 3, img: slide2, title: "View 2"},
          {id: 4, img: slide3, title: "View 3"},
          {id: 5, img: slide4, title: "View 4"},
          {id: 6, img: slide5, title: "View 5"},
        ],
        overview: "Experience contemporary elegance in this stylish apartment situated in Dubai Marina. Gaze out over the glistening waters as you savor the comforts of modern living. Enjoy the convenience of urban amenities combined with the tranquility of waterfront serenity. Your gateway to Dubai's finest offerings awaits in this exquisite residence.",
        kitchen: kitchen,
        bedroom: bedroom,
        bathroom: bathroom,
        dining: dining,
      },
      {
        id: 6,
        img: "./assets/villa.jpg",
        describe: 'Luxury Villa with Private Pool',
        locate: 'Emirates Hills, Dubai',
        lat: 25.075876, lng: 55.140154,
        beds: '6',
        baths: '7',
        garage: '12',
        size: '10000',
        price: '10,000,000',
        slides: [
          {id: 1, img: exterior, title: "Main View"},
          {id: 2, img: slide1, title: "View 1"},
          {id: 3, img: slide2, title: "View 2"},
          {id: 4, img: slide3, title: "View 3"},
          {id: 5, img: slide4, title: "View 4"},
          {id: 6, img: slide5, title: "View 5"},
        ],
        overview: "Immerse yourself in the epitome of waterfront living with this luxurious villa in Dubai Marina. Gaze out at panoramic sea views, relax in sprawling living spaces, and indulge in modern amenities. This is a rare opportunity to own a haven of tranquility amidst the dynamic energy of Dubai's premier residential district.",
        kitchen: kitchen,
        bedroom: bedroom,
        bathroom: bathroom,
        dining: dining,
      },
]

export default myProperties